name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core 
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
            3.1.x
            5.0.x
            9.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Create the package
      run: dotnet pack --configuration Release --no-restore
    #- name: Test
    #  run: dotnet test
