name: Release to Nuget

on:
  release:
    types: [published]


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core 
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
            3.1.x
            5.0.x
            9.0.x
        source-url: https://nuget.pkg.github.com/<owner>/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: dotnet build --configuration Release <my project>
    - name: Create the package
      run: dotnet pack --configuration Release
    #- name: Create Nuget Package
    #  run: dotnet pack -c Release /p:Version=${{ github.event.release.tag_name }} /p:PackageReleasesNotes="See https://github.com/JorgeBeserra/IqOptionApiDotNet/releases/tag/${{ github.event.release.tag_name }}"
    #  #working-directory: ./JorgeBeserra.IqOptionApiDotNet

    #- name: Archive Nuget Package
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: packages
    #    path: ./IqOptionApiDotNet/IqOptionApiDotNet/src/IqOptionApiDotNet/bin/Release/IqOptionApiDotNet.${{ github.event.release.tag_name }}.nupkg 
